config/routes.rb
Rails.application.routes.draw do

  
  get "like/create"

  devise_for :users
  root "posts#index"
  resources :posts do
    resources :comments
    resources :votes
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
	belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :comments
	has_many :votes

	def points
		votes.where(up: true).count  - votes.where(up: false).count
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	 has_many :comments
	 has_many :posts
end

app/models/vote.rb
class Vote < ActiveRecord::Base

	belongs_to :post
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	before_action :authenticate_user!

	def new
		@post = Post.find params[:post_id]
		@comment = Comment.new(post: @post)
	end

	def create
		@post = Post.find params[:post_id]
		@post.comments << Comment.create(params[:comment].permit(:title, :content,))
		redirect_to post_path(@post)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_action :authenticate_user!

	def new
		@post = Post.new
		@post.user
	end  

	def create
		@post = Post.create params[:post].permit(:title, :content)
		@post.user = current_user
		redirect_to '/posts'
	end

	def index
		@posts = Post.all
	end

	def edit
		@post = Post.find params[:id]

	end

	def update
		@post = current_user.posts.find params[:id]
		@post.update params[:post].permit(:title, :content)

		redirect_to '/posts'
	end

	def destroy
		@post = Post.find params[:id]
		@post.destroy

    redirect_to '/posts'	
	end

	def show
		@post = Post.find params[:id]
	end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController


	def create
		@post = Post.find(params[:post_id])
		Vote.create(up: params[:up], post: @post)

		redirect_to '/posts' 
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/like_helper.rb
module LikeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/comments/new.html.erb
<%=form_for [@post, @comment] do |form| %>
		
	Comment by: <%= current_user.email %>

	<br>
	<%= form.label :content, 'Comment' %>
	<%= form.text_area :content %>
	<br>
	<%= form.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SocialNews</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<% if user_signed_in? %>
	  <li>
	  	<%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
	  </li>
	  <li>
  		<%= link_to('Edit profile', edit_user_registration_path) %>
  	</li>

	<% else %>
	  <li>
	  	<%= link_to('Login', new_user_session_path)  %>  
	  </li>
	  <li>
 			 <%= link_to('Register', new_user_registration_path)  %>
  	</li>

	<% end %>

	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/like/create.html.erb
<h1>Like#create</h1>
<p>Find me in app/views/like/create.html.erb</p>

app/views/posts/_form.html.erb
<%= form_for @post do |form| %>
	<%= form.label :title %>
	<%= form.text_field :title %>
	<br>
	<%= form.label :content %>
	<%= form.text_area :content %>
	<br>
	<%= form.submit %>
<% end %>

app/views/posts/edit.html.erb
<%= render 'form' %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>


	<h1><%= link_to post.title, post_path(post) %></h1>
	<h2>Created <%= time_ago_in_words post.created_at %> ago</h2>
	<p><%= truncate post.content, length: 140 %></p>

	<h3 class='votes_count'><%= post.points %></h3>
	<%= button_to 'like', post_votes_path(post, up: true) %>

	<% if post.user == current_user %>
		<%= link_to 'Edit this post', edit_post_path(post) %>
		<%= link_to 'Delete this post', post_path(post), method: :delete, data: { confirm: 'Are you sure?' } %> 
	<% end %>
<% end %>
	
	<h3>
	<%= link_to "add a new post", new_post_path %>	
	</h3>

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/show.html.erb
<h1><%= @post.title %> </h1>

<p><%= @post.content %></p>


<h4><%= link_to 'Add a comment', new_post_comment_path(@post) %></h4>
 <% @post.comments.each do |comment| %> 

  

 	Comment by: <%= current_user.email %> 
 	<br>
		<p> <%= comment.content%> </p>
		
		<% end %>